# Generated by Django 4.2.30 on 2026-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bireportcache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bireportcache',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businessinsight',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bireportcache',
            unique_together={('business', 'report_type', 'period_start', 'period_end', 'parameters')},
        ),
        migrations.AddIndex(
            model_name='bireportcache',
            index=models.Index(fields=['business', 'report_type', '-updated_at'], name='bi_bireport_busines_51ae2e_idx'),
        ),
        migrations.AddIndex(
            model_name='bireportcache',
            index=models.Index(fields=['business', '-created_at'], name='bi_bireport_busines_f62232_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['business', 'is_active', '-created_at'], name='bi_business_busines_894c19_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['business', 'is_read'], name='bi_business_busines_01ee2f_idx'),
        ),
    ]
