# Generated by Django 4.2.30 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit (Average cost)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average cost * quantity_on_hand', max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('partial', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In - Purchase'), ('OUT', 'Stock Out - Sale'), ('ADJUST_IN', 'Adjustment - Increase'), ('ADJUST_OUT', 'Adjustment - Decrease'), ('RETURN_IN', 'Return from Customer'), ('RETURN_OUT', 'Return to Supplier'), ('DAMAGED', 'Damaged/Lost'), ('STOCK_TAKE', 'Stock Take Adjustment')], max_length=20),
        ),
    ]
