# Generated by Django 4.2.30 on 2026-05-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who processed this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='hr.employee'),
        ),
    ]
